apiVersion: v1
kind: Service
metadata:
  name: securityrat
spec:
  type: NodePort
  selector:
    app: securityrat
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 9000
      targetPort: 9000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: securityrat
spec:
  selector:
    matchLabels:
      app: securityrat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: securityrat
    spec:
      containers:
      - image: securityrat/securityrat
        name: securityrat
        env:
          # Use secret in real usage
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/securityrat?useUnicode=true&characterEncoding=utf8&useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: securityrat
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: JHIPSTER_SLEEP
          value: "10"
        ports:
        - containerPort: 9000
